[project]
name = "tunixhack"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "lmstudio>=1.5.0",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
